# Generated by Django 5.1.1 on 2024-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Isbn', models.CharField(max_length=30)),
                ('Publisher', models.DateField()),
            ],
        ),
    ]
